export enum Specialization {
   SPECIALIZATION_STUDIO = "SPECIALIZATION_STUDIO",
   SPECIALIZATION_PHOTOREPORT = "SPECIALIZATION_PHOTOREPORT",
   SPECIALIZATION_PRODUCT = "SPECIALIZATION_PRODUCT",
   SPECIALIZATION_LANDSCAPE = "SPECIALIZATION_LANDSCAPE",
}
